---
- hosts: clearwater_hosts
  remote_user: ubuntu
  name: Installing common features
  vars:
  - etcd_address: 172.16.0.135,172.16.0.195,172.16.0.170,172.16.0.92,172.16.0.132,172.16.0.49,172.16.0.150,172.16.0.152,172.16.0.59,172.16.0.234,172.16.0.137,172.16.0.190,172.16.0.233,172.16.0.78,172.16.0.247,172.16.0.116,172.16.0.125,172.16.0.44,172.16.0.114,172.16.0.169,172.16.0.104
  roles:
  - common

- name: Including package installation playbook
  import_playbook: package_installation.yml

- hosts: clearwater_hosts
  remote_user: ubuntu
  name: Set DNS configs
  vars:
  - dns_address: 192.168.200.171
  roles:
  - dns_config
 
- name: Set DNS server configs
  hosts: dns_host
  remote_user: ubuntu
  roles:
  - role: dns_server
    tags: 
    - dns_server

- hosts: bono_hosts
  remote_user: ubuntu
  name: modifing shared config
  roles:
  - shared_config


#- hosts: ellis_host
#  remote_user: ubuntu
#  name: Creating users
#  roles:
#  - create_users
